// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );

    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kX8VOTunCtkOq7JXe-5fQNjNBGF-vlQ',
    appId: '1:566361595542:web:c479d9c9ea2772331a6cb7',
    messagingSenderId: '566361595542',
    projectId: 'gymx-512a5',
    authDomain: 'gymx-512a5.firebaseapp.com',
    storageBucket: 'gymx-512a5.firebasestorage.app',
    measurementId: 'G-14DBEESVQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB2Sv3McK-_cUA-4ht1JVnRRZ3TPA_GC4',
    appId: '1:566361595542:android:391de494327109291a6cb7',
    messagingSenderId: '566361595542',
    projectId: 'gymx-512a5',
    storageBucket: 'gymx-512a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7K-V63J9NBm3bggLz9mqeaOxJeIJ5B0',
    appId: '1:566361595542:ios:a1f86d2f1b65deef1a6cb7',
    messagingSenderId: '566361595542',
    projectId: 'gymx-512a5',
    storageBucket: 'gymx-512a5.firebasestorage.app',
    iosBundleId: 'com.example.gymx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7K-V63J9NBm3bggLz9mqeaOxJeIJ5B0',
    appId: '1:566361595542:ios:a1f86d2f1b65deef1a6cb7',
    messagingSenderId: '566361595542',
    projectId: 'gymx-512a5',
    storageBucket: 'gymx-512a5.firebasestorage.app',
    iosBundleId: 'com.example.gymx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1kX8VOTunCtkOq7JXe-5fQNjNBGF-vlQ',
    appId: '1:566361595542:web:181c8ee9e9ebec4e1a6cb7',
    messagingSenderId: '566361595542',
    projectId: 'gymx-512a5',
    authDomain: 'gymx-512a5.firebaseapp.com',
    storageBucket: 'gymx-512a5.firebasestorage.app',
    measurementId: 'G-V3LYKPQ6X6',
  );

}